// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    [Migration("20240229203012_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4cfb20d-cbaa-400c-b81c-bbc8cd636937"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1a1a5de9-2719-4189-b9ec-08ba44412429"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8bbce6fc-27d6-475a-ac59-50f84da37db8"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b58655e7-2d33-4621-aebc-28b6aea6e70a"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("612cff23-7d0d-4063-becc-2e87afa35e81"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e374b540-7da3-4494-84fc-1bd6fabbe9dd"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e371fef0-ff08-4a69-9020-26322bb56a3b"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("59ab68d3-7056-4693-8c95-650257c3e38d"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("86592130-bb28-4876-80c9-c1ebb8dc0d46"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2503cd32-fc01-4e1f-977b-4a16f65f3050"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f39a5044-6185-487c-a7fb-a2331393fd7e"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7d67059f-314e-4454-8721-36051cbeb8b5"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1314f5f5-9c5e-47ab-8e26-c9ca17612483"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fb5195ac-9548-42d7-8c96-6206f9d540c5"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e52e11c8-a3a7-472b-b20e-5b3afe44c5ef"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("9c8476e8-2f74-4d04-94ef-9e32160cc808"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("acc7d658-e072-472b-a9ae-a9acff2c4b98"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("31b633f6-a4fa-439b-9979-77203715c695"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("242797cf-a2b6-491f-9b05-4df3117fbf95"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("9f8836cd-4f84-40b9-a41e-992f63640e13"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("12559925-9194-40cf-8f0c-fa544d3d71ac"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("592cbd51-3b40-4c6e-a715-382d5d7e3342"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b0061c95-8443-43ac-a6d0-6a74c69941e1"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("344e92f3-28b1-4b24-af1a-cf1acd4ad21c"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6874f56e-2ae1-4205-b2b2-043f07323e38"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("174f50a6-75ee-40a6-b1e6-b50abaafdcc9"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("aaf1318c-eda3-45bf-a7a3-6f0ae5e32da5"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c3686a8f-0867-4242-ae91-68f33c00cee5"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0745cad7-3d11-4e73-9543-00d5edbda252"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("cbe71899-3176-45e3-9dc1-30401d7e1b8c"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2889092f-d5dd-4c80-870b-17532d8ba6a0"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5540b2a9-8289-438c-a0ec-625ec6716edb"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ae3cbf1b-afbe-4990-a9c1-3abfca4b000c"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f2d9b367-feb4-4796-b3cf-8cfbee17d317"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b1283884-ebef-4ee2-b443-4751978a1e57"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("13f81e42-f546-4a94-a9b5-486018c3d78b"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fcabd3be-f31a-404b-8ba8-a4d33e845d04"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d13ea90f-c8e6-49d9-83cb-fc17e1f1147f"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("789bad19-ce2f-47e5-9692-e3d7a828c549"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("44c60e31-1f97-41d8-a70a-f28e03040ea0"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("01b6c29a-4da3-4391-a3ea-ff7384bd9a04"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("ede7e38d-4280-44be-8137-7a421b8b4931"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("ef9536d4-963d-4574-8d75-3e73630350ac"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("17e0ff0b-dcd1-4677-9ceb-c3fddea020c6"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("a7368ad0-3616-4d10-a7f1-e3ac244058b0"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("c7a2c582-4c6f-4d93-934c-b215e36ee835"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("1b4b372f-3cb4-43d7-ad73-b402c524f791"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8046eb04-cf2a-437b-8de2-d4521b00855c"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8d27a4d0-3719-4b16-b751-ad25fd45569c"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("86b06265-5f0f-4f4d-8586-d8f1f82d18c2"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("e7c2705d-14a1-472f-9f24-d0c3c107dd81"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("e6e7e504-4cfa-4dea-a21a-123e96d0fa5b"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("ea87906a-376e-42a1-a2dd-d0e6daa37414"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("7c1ba5ff-5a54-4700-9296-a7d694685c0b"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentTurnUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("CurrentTurnUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2c000aa-d2d7-48f8-9d25-f2d51698ba1c"),
                            CurrentTurnUserId = new Guid("97abf067-89b3-4bf9-84e3-22957dd328a2"),
                            IsPaused = true,
                            Name = "Game 1"
                        },
                        new
                        {
                            Id = new Guid("76782e5f-d778-4372-bc85-1a485c8870cf"),
                            CurrentTurnUserId = new Guid("cc9042a3-88e0-452c-8c41-7933369d74e2"),
                            IsPaused = true,
                            Name = "Game 2"
                        },
                        new
                        {
                            Id = new Guid("493840d6-297f-491d-9ba7-4e2873f7f2d8"),
                            CurrentTurnUserId = new Guid("86509782-5c97-4c3a-a323-9e71c31b7c1a"),
                            IsPaused = true,
                            Name = "Game 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("271f92f9-b58b-4990-95b1-93cf8c3b99f2"),
                            Description = "Game 1 Log",
                            GameId = new Guid("c2c000aa-d2d7-48f8-9d25-f2d51698ba1c"),
                            Timestamp = "12:00pm"
                        },
                        new
                        {
                            Id = new Guid("d182307f-5303-403c-af1a-ad0c5350af42"),
                            Description = "Game 2 Log",
                            GameId = new Guid("76782e5f-d778-4372-bc85-1a485c8870cf"),
                            Timestamp = "1:00pm"
                        },
                        new
                        {
                            Id = new Guid("45e0672f-867c-4533-8a71-11bdd1718b18"),
                            Description = "Game 3 Log",
                            GameId = new Guid("493840d6-297f-491d-9ba7-4e2873f7f2d8"),
                            Timestamp = "2:00pm"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71da6c30-3ba0-4888-82f8-60e203ad3213"),
                            GameId = new Guid("c2c000aa-d2d7-48f8-9d25-f2d51698ba1c"),
                            IsComputerPlayer = false,
                            UserId = new Guid("6b7b4763-43a0-4d50-9a17-d8cc7a7aa383")
                        },
                        new
                        {
                            Id = new Guid("b5143a2a-0933-47f4-b776-d719023ca5ba"),
                            GameId = new Guid("76782e5f-d778-4372-bc85-1a485c8870cf"),
                            IsComputerPlayer = false,
                            UserId = new Guid("6b7b4763-43a0-4d50-9a17-d8cc7a7aa383")
                        },
                        new
                        {
                            Id = new Guid("a4d3f636-4688-45e2-b7a2-2aa7d1e632b3"),
                            GameId = new Guid("493840d6-297f-491d-9ba7-4e2873f7f2d8"),
                            IsComputerPlayer = false,
                            UserId = new Guid("6b7b4763-43a0-4d50-9a17-d8cc7a7aa383")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e619d23-0a63-4e91-9797-129214646dd1"),
                            CardId = new Guid("e4cfb20d-cbaa-400c-b81c-bbc8cd636937"),
                            PlayerId = new Guid("71da6c30-3ba0-4888-82f8-60e203ad3213")
                        },
                        new
                        {
                            Id = new Guid("fc0ae598-69aa-482a-ae10-555ad316d2fb"),
                            CardId = new Guid("1a1a5de9-2719-4189-b9ec-08ba44412429"),
                            PlayerId = new Guid("b5143a2a-0933-47f4-b776-d719023ca5ba")
                        },
                        new
                        {
                            Id = new Guid("bbd4a514-5c53-4d48-a101-3c149ed7121d"),
                            CardId = new Guid("8bbce6fc-27d6-475a-ac59-50f84da37db8"),
                            PlayerId = new Guid("a4d3f636-4688-45e2-b7a2-2aa7d1e632b3")
                        },
                        new
                        {
                            Id = new Guid("34ade6fb-87dd-4d95-ad3b-1256cc6c3cea"),
                            CardId = new Guid("b58655e7-2d33-4621-aebc-28b6aea6e70a"),
                            PlayerId = new Guid("5f465ec3-0d6e-422c-8f57-d458bc97c0a1")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b7b4763-43a0-4d50-9a17-d8cc7a7aa383"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("863e81dd-7cdd-48c9-b814-0cc3c339a1e9"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("7a382949-07dd-4365-b0c4-e798e9b1a31f"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        },
                        new
                        {
                            Id = new Guid("093c9300-9b1a-41c5-9b1a-c7602484e79c"),
                            FirstName = "Bot",
                            LastName = "Bot",
                            Password = "OjGS4nkcV4YYDQImS16TRUBa+n0=",
                            Username = "Bot"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "CurrentTurnUser")
                        .WithMany()
                        .HasForeignKey("CurrentTurnUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblGame_CurrentTurnUserId");

                    b.Navigation("CurrentTurnUser");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
