// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    [Migration("20240228025300_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb2c9634-c202-4d16-bd6e-56b7159e440a"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("df111b79-c081-49e9-ae6f-7835bc1e399f"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e04ed4d6-135d-497a-9d43-5611a76e674f"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5cc34d20-9686-4675-b71b-a14a3c6333f8"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("00d35880-c512-4678-95a5-3b63cbbb7ff1"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("66eb5bd9-57c9-4bc5-859e-483e518a1ea6"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a85f7a09-bd26-4f2a-bcf5-73808ca49b61"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("deaca2e7-9a92-43c6-a4e5-f4153d045697"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("13770f24-d954-4a74-9153-5f035d533282"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fe885958-9a1c-4343-ac3f-495acffff3fb"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("231da35a-f1ff-4542-9d28-07e3721d4318"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ca96c588-4b15-40f5-be92-6b3f77b54834"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("52ba90cd-c065-43de-b5f7-f77d7fbb1799"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f3e48aaa-0dfa-4be3-adb1-028ea63cc37f"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("23fc303f-d48c-4eab-abfa-111a5a096b91"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b0942364-aa60-4af7-8e5a-b7fca02a47e8"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d90b4254-6bbb-4e87-baf2-92df7c1c295f"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4970edd2-e40d-4492-ae05-fb201aa3bb48"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5e1db2c6-ef61-4402-aeaa-d9901acab4f0"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7ab3377c-f96b-4c0c-a4d4-093b4b355432"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c9744766-8c73-424b-b1e5-bef0a6cee51e"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("9f64e441-0ba0-4eb5-9790-fb129794ad99"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("aea48f55-4bed-49e8-b876-33c2604a8430"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("15bb66ff-01f8-415a-a560-8d5e55bab93f"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a28f90d9-f965-4746-9373-147775c37505"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e0385216-8eb6-4486-827e-e87bf90b564c"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("adde9a4e-28e8-42e7-8cd8-c214bd4e320e"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f1946e04-03d1-4fc0-b45d-cf434eadf18b"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0dd55f99-fade-468f-9e5a-74b1c46aec73"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c46ff354-bfd3-4349-abb5-44da776319a0"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("3a740208-00b8-4a3b-bca5-2abdef34cf57"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f70b0dbf-815c-45ee-9168-fc851147b552"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("67383112-7d91-46bd-a3f0-a3a0cd9800d6"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d21d14c6-ee1d-4aa4-9c0e-2ab2bb2713e2"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8d2fed3f-2201-4bcc-bc58-499298713cf4"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c0fd2a04-48ab-42fc-b0ab-572bca6fb767"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("179b5841-9b5e-4c9c-ad14-d71ec89c62f8"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e762b005-88fe-4585-8798-fea1939c45f0"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ba7b21ba-825b-4b08-bb8a-0ea2f5edeb4b"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("068e1ab8-567d-48e6-bb8c-61fb81ebcf54"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("227533e4-3178-44b5-bde2-9e132c12e3fa"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("512d15eb-a55c-4b2d-a675-e7715d54a6f4"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("6c9c67d1-3a3b-4b14-9f00-cfe42894f2a8"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("0fea493e-5670-49bb-bc0f-9d7d2f41483b"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("55297fb7-bef4-4077-b93e-4e506c18667b"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("c35f0866-97ac-4952-ab66-ccf011cc4c8b"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("c4819857-623c-4533-aefd-bb4e959a7468"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("0315628b-e551-43d8-9290-f40cd711024f"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("0cd2d42d-5d73-466b-bd37-7bbce4382bfb"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("9cd58f09-ee28-4376-9f9f-d82e335b69fc"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("2a70ca95-4647-48a0-9d3d-047fc4ef4b0e"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("b567aff9-7f18-4944-8e04-6a5ba2ffada4"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("6aefab1b-78cf-436f-a924-6ae5547718fe"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("da49f459-c9d1-40ee-9d7a-5801bc8f3c17"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentTurnUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("CurrentTurnUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80aa3513-a6c1-4d5b-9503-a7b93f4f1722"),
                            CurrentTurnUserId = new Guid("82e4827e-2be9-415c-b566-34326193bd94"),
                            IsPaused = true,
                            Name = "Game 1"
                        },
                        new
                        {
                            Id = new Guid("7ab98732-4e76-48e0-b318-be1cfc7dbec1"),
                            CurrentTurnUserId = new Guid("b27a1e23-ace2-43ea-b9a3-e2468038715c"),
                            IsPaused = true,
                            Name = "Game 2"
                        },
                        new
                        {
                            Id = new Guid("2a7e2c5c-f56f-473e-9f7f-971e941bef56"),
                            CurrentTurnUserId = new Guid("8935e450-d982-4e2a-931f-2c45c4deed5a"),
                            IsPaused = true,
                            Name = "Game 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7db0068e-e511-4472-97a1-190ead14cfa7"),
                            Description = "Game 1 Log",
                            GameId = new Guid("80aa3513-a6c1-4d5b-9503-a7b93f4f1722"),
                            Timestamp = "12:00pm"
                        },
                        new
                        {
                            Id = new Guid("4694f18d-1737-4c6c-bd6f-060cdaca9c15"),
                            Description = "Game 2 Log",
                            GameId = new Guid("7ab98732-4e76-48e0-b318-be1cfc7dbec1"),
                            Timestamp = "1:00pm"
                        },
                        new
                        {
                            Id = new Guid("ebbd152a-cea3-49b2-8018-18f9f2b20f29"),
                            Description = "Game 3 Log",
                            GameId = new Guid("2a7e2c5c-f56f-473e-9f7f-971e941bef56"),
                            Timestamp = "2:00pm"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("176a7e96-ad2b-4a25-9f60-7f427a64329a"),
                            GameId = new Guid("80aa3513-a6c1-4d5b-9503-a7b93f4f1722"),
                            IsComputerPlayer = false,
                            UserId = new Guid("417658d1-6f0a-4e62-9626-0e134175d335")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4d50d1e-cf6f-4ff9-8b82-6f3c0f0cec11"),
                            CardId = new Guid("eb2c9634-c202-4d16-bd6e-56b7159e440a"),
                            PlayerId = new Guid("176a7e96-ad2b-4a25-9f60-7f427a64329a")
                        },
                        new
                        {
                            Id = new Guid("ee2adb4f-4907-45c1-b26b-ba76b146b75d"),
                            CardId = new Guid("df111b79-c081-49e9-ae6f-7835bc1e399f"),
                            PlayerId = new Guid("c490eb37-b2c7-4891-af40-8eff38f21b98")
                        },
                        new
                        {
                            Id = new Guid("fa03c33c-3907-41d0-a307-782dcbc8aba2"),
                            CardId = new Guid("e04ed4d6-135d-497a-9d43-5611a76e674f"),
                            PlayerId = new Guid("9ccf76ce-89eb-4756-8087-6d6305e3db42")
                        },
                        new
                        {
                            Id = new Guid("d140daf6-525f-4369-998c-7f9a1eb05115"),
                            CardId = new Guid("5cc34d20-9686-4675-b71b-a14a3c6333f8"),
                            PlayerId = new Guid("45b3906f-d48c-408f-be8f-8fa77adbe06d")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("18069ff5-26d7-48a8-ab5f-148b3d2a6938"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("dec08658-00c3-414a-b2dc-e583582f981b"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("842e1180-cd5d-46e0-bd4e-cd0944a82fa2"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        },
                        new
                        {
                            Id = new Guid("4d32d551-416b-41f3-8595-d7289673d0c4"),
                            FirstName = "Bot",
                            LastName = "Bot",
                            Password = "OjGS4nkcV4YYDQImS16TRUBa+n0=",
                            Username = "Bot"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "CurrentTurnUser")
                        .WithMany()
                        .HasForeignKey("CurrentTurnUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblGame_CurrentTurnUserId");

                    b.Navigation("CurrentTurnUser");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
