// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    [Migration("20240227022222_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("39daaf72-e7ca-44c4-8c25-642a55882a71"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("44f2ffaf-bfca-41a9-8cf0-6dd1df64b472"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4b0d2d66-30a2-47b7-a881-b9fa6a2d8cb5"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("3f04e93a-ad28-4530-8d23-a33728a0fe96"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4f90a2dd-da89-4121-a785-da08762bb95a"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("3bbd6e0c-91de-4c34-9b4c-4c41c5d8a425"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c98c82d4-3579-4edf-af20-46554c494b9f"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("26f1f598-f4d5-4ac4-9420-f7c4d0e0b9d2"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d3f1d2ee-ac37-45dd-8bfa-5113a0e095b0"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("db4933d9-3f4b-4f4d-9ad6-a690238ff0ce"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("74d8aa4b-7b27-433d-b05d-b2d569350480"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("484616b2-c20a-4ac3-a85c-377941a17853"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4aee857f-0bc2-47d0-a5fb-e951769c5702"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0d074144-1008-40b8-b138-5d9ed0acbf30"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("633b0239-db28-4a3b-a5bb-35b1e95f42c8"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("666bf31a-60c9-4667-937c-06f78b586fcb"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a32f68d3-7f0f-41b3-a441-e4749b4df7e9"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4b4308bb-c89d-47d0-9488-1839cfa09d87"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("13ab9dbc-43fa-4dca-9209-b5e1ff479b81"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("23290282-633a-4f71-8182-24f8918e58e6"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("bc098d91-9019-46a7-890e-06efb9ce7a9d"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a49648d0-7cd3-474a-a70c-129de3b2595f"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1b26c5fb-7f77-4b84-be78-7173bb1a3389"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e3b9b5e1-1a11-4c3c-9529-b8bcf9de649a"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a58bb66f-906d-42a9-94e1-1e989a1b0cb3"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0fc2d153-d59a-4463-b024-6d4540d8e523"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0c3a6c0c-70d0-41c4-86f7-f737f465d4da"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8d334b38-6403-4bc4-a884-5ece07ae9689"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2f87b0a8-36ee-4f04-9dfd-f9dc153e42bd"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4ddb183f-8f97-4591-b324-a74353ca3e32"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a2136694-6956-4b2c-b554-af2c648b0de2"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("eab658f9-c639-4f8f-80b7-5bd89077432c"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8a57f82b-99eb-458f-ae20-fd0925b72fb9"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c5f656a3-3037-492e-8fe2-d520b5415dcc"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d274d121-237e-4cc3-9d19-6522428b4521"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("87e51800-da80-439d-bda4-fb291a7c9f43"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b2cf32cc-2333-493b-b3c6-0ac094975643"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d95ccbac-d823-4812-97c8-900cc1d27650"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("969b88ed-d6dc-49a1-9f6a-f05906620ddd"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7892178d-e14c-4057-9c2d-95c116e85653"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6455e8b2-170a-4d5d-b8de-8177dafdd0f7"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("3120e7fa-e9b0-41b1-9a1f-b752d1c9af8b"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("38e5c006-9c02-4fb5-87a6-c5a1fb6192c7"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("06d8ddbc-892d-40dc-89d0-ebc6c9e619c2"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("333ef719-1d89-419f-a281-e3cb355021be"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("7718b355-ce98-4619-99b8-baeee863d858"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("312ba25f-141d-4931-8807-7f4d0656ed2b"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("3560b463-4dcb-47ba-ae43-fdb3ed45d4d5"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("6a95098a-88cb-4431-b7af-b650133fcac6"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("7ace504b-0a95-4fbf-aa38-c93731d7d8e5"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("766ea8e1-c4cd-46c7-9089-670b9c6a1479"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("50822bdb-c5d1-46d1-8b29-7397977aee36"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8aa442dd-cd10-4070-b08c-7e3b05b07227"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("85490b6e-39fa-4818-80a9-924f4e803800"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("UserId");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b34baa9-0d88-45b8-9c95-f25128f6b750"),
                            IsPaused = true,
                            Name = "Game 1",
                            UserId = new Guid("ea151920-35a2-4aa2-a106-b1f1caeec47c")
                        },
                        new
                        {
                            Id = new Guid("1e8ae97d-6eeb-466d-a66e-855272510d4b"),
                            IsPaused = true,
                            Name = "Game 2",
                            UserId = new Guid("0bf39821-f411-4116-8446-9334296c02ff")
                        },
                        new
                        {
                            Id = new Guid("ff81d7ed-ac81-4a82-aa2d-f05ebbaa8842"),
                            IsPaused = true,
                            Name = "Game 3",
                            UserId = new Guid("516e98d5-f40a-46cf-8143-0be1f5b24020")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2adebf95-50d8-482d-b836-ae28203af14a"),
                            Description = "Game 1 Log",
                            GameId = new Guid("9b34baa9-0d88-45b8-9c95-f25128f6b750"),
                            Timestamp = "12:00pm"
                        },
                        new
                        {
                            Id = new Guid("3ce261e5-0ea0-4cf6-b980-fefa4a6b8d74"),
                            Description = "Game 2 Log",
                            GameId = new Guid("1e8ae97d-6eeb-466d-a66e-855272510d4b"),
                            Timestamp = "1:00pm"
                        },
                        new
                        {
                            Id = new Guid("3c18c764-4d18-4d5e-8d1f-f2b3abf49e02"),
                            Description = "Game 3 Log",
                            GameId = new Guid("ff81d7ed-ac81-4a82-aa2d-f05ebbaa8842"),
                            Timestamp = "2:00pm"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fa54f9f-4577-40b4-ac2b-77318994be1e"),
                            GameId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsComputerPlayer = false,
                            UserId = new Guid("ea151920-35a2-4aa2-a106-b1f1caeec47c")
                        },
                        new
                        {
                            Id = new Guid("0880134e-3e64-417f-b397-99903cf8afc3"),
                            GameId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsComputerPlayer = false,
                            UserId = new Guid("0bf39821-f411-4116-8446-9334296c02ff")
                        },
                        new
                        {
                            Id = new Guid("8f5f768f-6c4a-4588-b475-36cdd06b1186"),
                            GameId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsComputerPlayer = false,
                            UserId = new Guid("516e98d5-f40a-46cf-8143-0be1f5b24020")
                        },
                        new
                        {
                            Id = new Guid("b0fc5883-82ad-46de-a01e-e062a96dc09b"),
                            GameId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsComputerPlayer = true,
                            UserId = new Guid("86cf474e-fc40-4171-a3ab-a9c821b6ec14")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("acfb29d5-a511-45a6-bfd1-43329a803120"),
                            CardId = new Guid("39daaf72-e7ca-44c4-8c25-642a55882a71"),
                            PlayerId = new Guid("9fa54f9f-4577-40b4-ac2b-77318994be1e")
                        },
                        new
                        {
                            Id = new Guid("8f9ca24a-5769-46af-b5bf-8528c0df5097"),
                            CardId = new Guid("44f2ffaf-bfca-41a9-8cf0-6dd1df64b472"),
                            PlayerId = new Guid("0880134e-3e64-417f-b397-99903cf8afc3")
                        },
                        new
                        {
                            Id = new Guid("e8707f9f-9d06-4f78-aab7-310026c3bd81"),
                            CardId = new Guid("4b0d2d66-30a2-47b7-a881-b9fa6a2d8cb5"),
                            PlayerId = new Guid("8f5f768f-6c4a-4588-b475-36cdd06b1186")
                        },
                        new
                        {
                            Id = new Guid("1382fddb-1a49-46a0-8d46-a1b6323a8b68"),
                            CardId = new Guid("3f04e93a-ad28-4530-8d23-a33728a0fe96"),
                            PlayerId = new Guid("b0fc5883-82ad-46de-a01e-e062a96dc09b")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("592a79db-625a-407a-a372-d93de366cd6b"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("92777b4b-6594-4a00-b76c-b3a9eab276c7"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("c485bf94-5c0f-4b63-8aa5-e8b95649e594"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        },
                        new
                        {
                            Id = new Guid("0dde41bc-4260-4524-b1f1-4543fac7fc53"),
                            FirstName = "Bot",
                            LastName = "Bot",
                            Password = "OjGS4nkcV4YYDQImS16TRUBa+n0=",
                            Username = "Bot"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "CurrentTurnUserId")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGame_UserId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", null)
                        .WithMany("Games")
                        .HasForeignKey("tblUserId");

                    b.Navigation("CurrentTurnUserId");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGame_Id");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblUser_Id");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
