// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    [Migration("20240322154343_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80d586d0-bce8-4844-8fe4-70a882d4b07e"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0a0bf98d-1f37-439e-a7fb-a8e2482b4568"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("621233ac-94ae-4d9c-9cd6-a858416094bd"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5cc3d870-ee43-4068-b22a-ee13a293df97"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("db6e6807-9a8f-40fe-a0d6-0f81e7708733"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1001a5f1-fdb0-4a5f-8050-158c76afea8d"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a8f37f6a-dec0-41c0-ae05-5e12038787e6"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a461e592-9818-4805-8591-48abbc5c663f"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("67c6efad-34a0-4e95-acc5-b816b81437c8"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0fdc95be-659e-47ed-8ced-0151868cd0c8"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ce15d37b-f01d-4a72-9d17-aa49e6d0ce84"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("105e3dfa-9d95-4b8f-8af9-2aa31591031d"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b019c066-eb18-4cee-8277-88820cfc4006"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c8b4b27d-3672-40d3-82f3-e0048b4d14a5"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4eeb491a-c832-45a4-912c-6fa8e64e2489"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fc377cd5-4746-4943-a5d5-d6c1d4408538"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e3911b1c-55fc-4c46-86e3-5844d56d1737"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("3b68e4a0-8d3f-410e-867e-d6fa2fb4dcda"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("39116ec2-7044-40f0-ba52-5e36a48fc7cd"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("873f2e60-d074-4bb4-8485-5e1bb7968fe1"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("9d1a22a5-9ba4-4288-bf22-5b2c7d3a92b0"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c90504a1-40b7-4647-a6fd-89b3c223e15a"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fd772a05-ca7f-4539-bfa3-ddc88c991aca"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("84b0d102-e799-4c1c-ada6-2aeead702a40"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ff89dcc1-6127-4f58-81f4-326dd139732c"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d1efef89-e77d-4911-8515-1eb939e193a8"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f9998be9-fa00-4283-9e97-4493e52e570e"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8f25b3cb-053c-4d48-b3eb-8c0f41abdf98"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("95af9d2b-05ed-4157-8c8b-705518ab6f0f"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4ecfa821-705f-4e74-a1e3-775251352877"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a970efb5-e266-4f6f-a957-21178c7cc3c3"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ce14a598-029d-4c38-9113-4993f9a97c83"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d6727c5e-1771-4206-a80a-ad437e3aee0f"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("346163c0-5f73-44dd-b8d8-4ae2a1e2e855"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("878c6a0f-884f-4369-b2bd-45f34695f03d"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e99c5314-b1c8-4833-a36d-2313fc9dae8a"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("cb95f7d5-410a-4f93-9b05-1ebbf7336d9a"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7696f5a6-eacb-42a6-83ab-e7ea60991a08"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("827f9491-5a50-4f9e-a350-b5f1d3dae613"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ea8accd5-84f2-4b93-ae5a-bd22855167de"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8abab812-bcf7-4ac4-bd6c-3db71ac1c41a"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8110c0f3-8791-4c41-b071-d6a16faca9d8"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("69a8fdeb-d225-4145-8201-935604b1c0f5"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("42240731-b5a3-44cd-a60e-5b52cc8d9379"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("3a8598c0-6af6-431f-969c-454ef9ca3d93"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("87915ac9-5cbc-445f-a5e1-d6656fec6149"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("0e52da78-6e55-4fd6-bbc1-34832f366ac5"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("bf8781a4-0bcc-454d-863b-9241c7901dab"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("335a9c12-62f8-4dbc-93c8-3357ed1ec3ff"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("fdf92d0c-daef-4070-975e-fa1d1b0b4db8"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("f370a50d-3e3e-449c-96eb-23191cfbbafa"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8d6fcdc0-829d-4907-9e78-fb5d4e033f76"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("85cacf37-0a97-4ca3-b713-6f2b481c680d"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("fff9789a-7b5e-4cbf-ae09-f73a043206b3"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentTurnUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("tblPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("tblPlayerId");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5971fc34-6d11-463a-9b91-d01082117323"),
                            CurrentTurnUserId = new Guid("37436d31-f5fe-419e-bfe2-a1050c6ed2ce"),
                            IsPaused = false,
                            Name = "Test Game 1"
                        },
                        new
                        {
                            Id = new Guid("86a735e2-5d90-4e0f-8846-4db798f0adf9"),
                            CurrentTurnUserId = new Guid("7dabe075-2d31-4532-879e-be086998d436"),
                            IsPaused = false,
                            Name = "Test Game 2"
                        },
                        new
                        {
                            Id = new Guid("f3f66fd2-6ea1-4474-9923-1f69190d5564"),
                            CurrentTurnUserId = new Guid("2a8de7bf-a0c2-4d09-bac9-4fbc522b4bff"),
                            IsPaused = false,
                            Name = "Test Game 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01313c0c-3f0c-4ad2-b763-787674671bde"),
                            Description = "Test Game Log 1",
                            GameId = new Guid("5971fc34-6d11-463a-9b91-d01082117323"),
                            Timestamp = "Test Stamp 1"
                        },
                        new
                        {
                            Id = new Guid("3cbf1794-d7d0-45fc-9f24-be4560006e22"),
                            Description = "Test Game Log 2",
                            GameId = new Guid("86a735e2-5d90-4e0f-8846-4db798f0adf9"),
                            Timestamp = "Test Stamp 2"
                        },
                        new
                        {
                            Id = new Guid("ebe35040-dd07-402b-ad16-f6f187dd02de"),
                            Description = "Test Game Log 3",
                            GameId = new Guid("f3f66fd2-6ea1-4474-9923-1f69190d5564"),
                            Timestamp = "Test Stamp 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b895363f-84ec-4cbb-a623-a5ea04d21372"),
                            GameId = new Guid("5971fc34-6d11-463a-9b91-d01082117323"),
                            IsComputerPlayer = false,
                            UserId = new Guid("37436d31-f5fe-419e-bfe2-a1050c6ed2ce")
                        },
                        new
                        {
                            Id = new Guid("8e975ffc-73db-43ce-8674-57ec9bec0809"),
                            GameId = new Guid("86a735e2-5d90-4e0f-8846-4db798f0adf9"),
                            IsComputerPlayer = false,
                            UserId = new Guid("7dabe075-2d31-4532-879e-be086998d436")
                        },
                        new
                        {
                            Id = new Guid("d2953128-01a3-454a-ae8a-b668d126af7e"),
                            GameId = new Guid("f3f66fd2-6ea1-4474-9923-1f69190d5564"),
                            IsComputerPlayer = false,
                            UserId = new Guid("2a8de7bf-a0c2-4d09-bac9-4fbc522b4bff")
                        },
                        new
                        {
                            Id = new Guid("158a0f4a-e308-4417-b459-47a8868d5d72"),
                            GameId = new Guid("5971fc34-6d11-463a-9b91-d01082117323"),
                            IsComputerPlayer = true,
                            UserId = new Guid("35c9b800-1a23-4f6a-a4ea-90db6a84fa59")
                        },
                        new
                        {
                            Id = new Guid("183abdac-4c5f-476c-ac7a-9bc7bfadf652"),
                            GameId = new Guid("86a735e2-5d90-4e0f-8846-4db798f0adf9"),
                            IsComputerPlayer = true,
                            UserId = new Guid("35c9b800-1a23-4f6a-a4ea-90db6a84fa59")
                        },
                        new
                        {
                            Id = new Guid("23710c28-3420-4016-b0c5-7998a20df35f"),
                            GameId = new Guid("f3f66fd2-6ea1-4474-9923-1f69190d5564"),
                            IsComputerPlayer = true,
                            UserId = new Guid("35c9b800-1a23-4f6a-a4ea-90db6a84fa59")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f11fbe5f-e99c-4c1d-87d3-8b31b68dc2ea"),
                            CardId = new Guid("80d586d0-bce8-4844-8fe4-70a882d4b07e"),
                            PlayerId = new Guid("b895363f-84ec-4cbb-a623-a5ea04d21372")
                        },
                        new
                        {
                            Id = new Guid("28708c77-6363-47c7-90c2-5d43ce102cee"),
                            CardId = new Guid("0a0bf98d-1f37-439e-a7fb-a8e2482b4568"),
                            PlayerId = new Guid("8e975ffc-73db-43ce-8674-57ec9bec0809")
                        },
                        new
                        {
                            Id = new Guid("ff089931-a13f-4b80-9bfa-883d473c858c"),
                            CardId = new Guid("621233ac-94ae-4d9c-9cd6-a858416094bd"),
                            PlayerId = new Guid("d2953128-01a3-454a-ae8a-b668d126af7e")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("37436d31-f5fe-419e-bfe2-a1050c6ed2ce"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("7dabe075-2d31-4532-879e-be086998d436"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("2a8de7bf-a0c2-4d09-bac9-4fbc522b4bff"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        },
                        new
                        {
                            Id = new Guid("35c9b800-1a23-4f6a-a4ea-90db6a84fa59"),
                            FirstName = "NPC",
                            LastName = "NPC",
                            Password = "8M1CByOq6EARbI7321yvHg3/Ku8=",
                            Username = "NPC"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", null)
                        .WithMany("Games")
                        .HasForeignKey("tblPlayerId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", null)
                        .WithMany("Games")
                        .HasForeignKey("tblUserId");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
