// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    [Migration("20240228031246_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ed12283-e83a-47c4-b8eb-1065da1a9ecb"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7330b2c6-e199-4419-abf6-ea781a461eda"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("bf974281-f393-4075-b632-3c4279bbaa1d"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ecf7735d-b887-45c6-8206-0feb3eb24bcd"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4a924450-1485-47f8-a2ee-ea34a084b26b"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("beca98e7-0145-46b0-a80d-5f1a4329c3f2"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a32ad6da-1569-44c7-a4f2-5ebd923bd72d"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d0ff2336-2de0-4ee1-a6a8-c558019817db"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ff37fd44-e053-4d27-aff7-0be8e180c2c5"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("677ffb76-9cc9-426e-8cbb-67f197b18619"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("788d6820-8f92-43b1-9d37-f7175902e32e"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("378e495e-c8f2-41a9-a759-3c2bd929fccc"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a7b46dad-8b44-43fb-b27c-adfd455c6eed"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e8dec34a-fe6d-4398-9db4-0e5595f6a45c"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ae0a3b13-bcd0-4f45-b17b-2ff93a44e9e3"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0a857abf-af8c-48ad-8cdc-08d9506e82a0"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d7d4ebe4-2b92-4578-8e3f-209621a754d7"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("86bdfce8-2b8c-497f-b927-19be6b118155"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fb5c4fbb-7be9-456e-ae62-1096e1ddefc0"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d891738b-00e2-4271-acf4-6cef6a0d5cdc"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("acb45178-ccf3-4dd5-945f-8d990872e8e3"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5c249c9f-3db3-49d7-90e0-bb16b0100580"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5f8a0ff7-fda1-4e86-9c16-b0a92c6ef07c"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c41ee893-d479-4eb1-809d-2c63aa240c83"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c365b2e4-4923-4915-844e-1263484d5708"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5cc0af94-7df4-4dbe-8727-5c19afb9d5bd"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("362bb8f0-23e1-48b4-8d29-b43525e41f7f"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5ae0638b-79e8-4fc6-9b5f-63b8b114228c"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7b2a5a36-230f-4e36-a718-2f1767d94360"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7e952559-d3eb-4a6f-b339-f2229928ec88"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8ef0604b-3b20-45a3-ba56-23601e5d230f"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("56f1584d-0ee0-4f40-bc6e-607bf8820b5b"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("566a834a-0f8d-4d61-b533-d756b302f994"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("bcad1f07-38a5-490b-9143-5d6c9734541e"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4ac5810b-52c6-44f0-8081-0aad3c39acc5"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("08c8cb79-c74d-46f8-9f73-0f3f0659879e"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0b254543-651c-467e-b405-2a84fd01ce6a"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a31cf900-152d-4de5-b113-4a6d0e8023c2"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("cc5ab6ab-0e49-4b70-99dd-d02e62cbdda5"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("04f3efb5-1422-4bea-a194-98e7e26f2a1c"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f2049347-7298-4b18-8261-c4a4d577e16d"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("d55388bf-76f6-4692-b60b-e3b78437fc2f"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("7aaa4331-d6ea-4fed-925f-50fd0412cb57"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8df37899-2edd-410e-9142-1dd3d6c17ee9"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("cf91378a-3eb4-4cb9-bcb4-c737c8b7b4f3"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("82ce1671-2cd6-4cf5-b384-0da35838b918"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("5c92449c-e480-42a3-b738-37747059672e"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("25bdba97-856e-4b46-86d0-7c8412aea258"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("a93860a1-385b-4f55-8c1f-476bd55706f4"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("689e9a98-a4a7-49f5-919c-34aa92005817"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("7465734d-0b2d-4119-9225-6c371b4734e1"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("f1982bfb-f6fa-461b-ab43-b6b7ab778032"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("99926afe-18fd-4375-92ae-58724ddfaf03"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("97e423e0-2e51-4550-992c-e547d09fce20"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentTurnUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("CurrentTurnUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cf61197-9e20-473b-bdac-a519966269c2"),
                            CurrentTurnUserId = new Guid("cbb644a5-cfc3-40c7-b040-53a4d18f449e"),
                            IsPaused = true,
                            Name = "Game 1"
                        },
                        new
                        {
                            Id = new Guid("5b34913e-55f9-467b-9d4d-0fd001705f60"),
                            CurrentTurnUserId = new Guid("76a6ab59-d7ed-441f-bd99-78c0c76fda74"),
                            IsPaused = true,
                            Name = "Game 2"
                        },
                        new
                        {
                            Id = new Guid("7ed005b7-bcde-43f1-966d-657eb89bc308"),
                            CurrentTurnUserId = new Guid("cec2c1a1-1c72-4a9c-8724-76aa74a03396"),
                            IsPaused = true,
                            Name = "Game 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a810c34a-7798-4a2a-a176-e390bd1352a3"),
                            Description = "Game 1 Log",
                            GameId = new Guid("6cf61197-9e20-473b-bdac-a519966269c2"),
                            Timestamp = "12:00pm"
                        },
                        new
                        {
                            Id = new Guid("fa2b64ee-47e3-451a-8570-18cd65d5bfee"),
                            Description = "Game 2 Log",
                            GameId = new Guid("5b34913e-55f9-467b-9d4d-0fd001705f60"),
                            Timestamp = "1:00pm"
                        },
                        new
                        {
                            Id = new Guid("69770706-a303-4f31-94ce-ba82356510fc"),
                            Description = "Game 3 Log",
                            GameId = new Guid("7ed005b7-bcde-43f1-966d-657eb89bc308"),
                            Timestamp = "2:00pm"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("58413ad9-2faf-4f69-8aa2-8a830d50de14"),
                            GameId = new Guid("6cf61197-9e20-473b-bdac-a519966269c2"),
                            IsComputerPlayer = false,
                            UserId = new Guid("d0d9b86c-d4c4-475d-abd9-5b67ce137eb7")
                        },
                        new
                        {
                            Id = new Guid("4dcabcc3-f34f-48c8-b037-021b2f4993cb"),
                            GameId = new Guid("5b34913e-55f9-467b-9d4d-0fd001705f60"),
                            IsComputerPlayer = false,
                            UserId = new Guid("d0d9b86c-d4c4-475d-abd9-5b67ce137eb7")
                        },
                        new
                        {
                            Id = new Guid("87441425-7c40-433d-9561-c228e0e59d5a"),
                            GameId = new Guid("7ed005b7-bcde-43f1-966d-657eb89bc308"),
                            IsComputerPlayer = false,
                            UserId = new Guid("d0d9b86c-d4c4-475d-abd9-5b67ce137eb7")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6532b3e9-a048-4483-b8e3-168e1a247d8b"),
                            CardId = new Guid("8ed12283-e83a-47c4-b8eb-1065da1a9ecb"),
                            PlayerId = new Guid("58413ad9-2faf-4f69-8aa2-8a830d50de14")
                        },
                        new
                        {
                            Id = new Guid("d586c189-6e5f-4f3b-9d63-bc677033bba9"),
                            CardId = new Guid("7330b2c6-e199-4419-abf6-ea781a461eda"),
                            PlayerId = new Guid("4dcabcc3-f34f-48c8-b037-021b2f4993cb")
                        },
                        new
                        {
                            Id = new Guid("42303d56-a373-48ad-9fcc-95593dbfa335"),
                            CardId = new Guid("bf974281-f393-4075-b632-3c4279bbaa1d"),
                            PlayerId = new Guid("87441425-7c40-433d-9561-c228e0e59d5a")
                        },
                        new
                        {
                            Id = new Guid("05f7c37b-ee84-4c80-8ca4-8eadbb767667"),
                            CardId = new Guid("ecf7735d-b887-45c6-8206-0feb3eb24bcd"),
                            PlayerId = new Guid("7387595f-6e37-432a-be37-298449e8947b")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0d9b86c-d4c4-475d-abd9-5b67ce137eb7"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("84826276-af90-4f04-a43c-33ccb0d4a668"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("9297a543-3d3d-4372-8ff0-3233d28571f3"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        },
                        new
                        {
                            Id = new Guid("434b40b7-aa4d-4aeb-b719-178706cb90cb"),
                            FirstName = "Bot",
                            LastName = "Bot",
                            Password = "OjGS4nkcV4YYDQImS16TRUBa+n0=",
                            Username = "Bot"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "CurrentTurnUser")
                        .WithMany()
                        .HasForeignKey("CurrentTurnUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblGame_CurrentTurnUserId");

                    b.Navigation("CurrentTurnUser");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
