// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    [Migration("20240318182048_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3879e895-5337-4f22-bd6c-ef640630c4c1"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4ea58f20-d972-477e-a3cd-86b4cd9a8054"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b28ce706-42f1-4f32-b184-541e4f96c928"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("005be997-3f9e-417c-87dd-53eba21b128e"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ec8a275b-dfdd-4ec1-9921-8956e9694aff"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5e2d8d78-99f5-4db2-8504-8c9ab743eab3"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1927c2dc-11d0-439c-8e4e-bf4140d4759e"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("189e3669-55dd-49f1-8741-f814b853083c"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8356d5b7-0453-4898-b613-f0f317bf0585"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0ee3a9af-656b-4223-b483-143629d3e02e"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0ef5b1b6-1b58-4b19-93bc-a65e8643ea39"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("dfd18ed8-cc4d-45c5-93a0-c3811d3bfa5e"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c1d0e3e1-546f-4227-9581-14040f7922d9"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("07035940-3b7d-4180-af9e-e93d03da6514"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fb8d0e39-a4e8-4c9c-84b3-e9460b6b22c7"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f7ad886d-0fbe-40af-9860-a20d57759211"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("317f26e6-e6b1-4498-a5da-4037657252a4"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c2640988-74a7-4192-8544-61bffdd5db04"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e63cf21a-5a64-4ea4-8509-56b9fd058adf"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("06951e5a-ac87-4184-a5f3-e003eaae4814"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0b9fa0d5-b8e2-41f3-b4c3-3dcef6f7b224"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1e2ae1f2-0a41-414a-a912-aecb1f6a8bc7"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("3bbd7dc3-e8f4-47a7-b0bf-aa05846b58a8"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("243e8140-2c5b-47c7-90da-7dd7ea1f5086"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f0ad5c83-1f91-497b-8e52-2f74286c7321"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ddced8ab-d182-421e-8d2a-2cc2d77d4c92"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("51bd92d7-f459-4a92-8e76-dc208edcd238"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2fb21530-d491-4852-8077-ef645cab47da"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("dc298c72-6ba4-4a63-ae29-7026ed95649f"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("9faf327b-7ea8-4b7a-8a93-f26e0f8cb4be"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b30f0180-5248-44c0-8305-25026d214ab5"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("25a9371d-5bbe-463e-be39-0b2e4cfb9314"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f9c257f9-725d-4173-8feb-d066921fd57e"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fc5b941e-2de1-47df-a67e-5101e44c126b"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5cb432e8-ee95-472e-840e-c90d14351248"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("01f31309-f207-462e-a6e7-f61f929a22d1"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("18fd16eb-426b-42a6-af46-9238e16005db"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("79273477-0e2e-4b41-849f-1db836973d12"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("316c9600-6a5b-4434-9515-7bf0d0468ce0"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("5f2e8866-2bc8-4185-8b98-79c11811bd37"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("00a9fa99-83b0-4f7b-823e-18db4eb6b6fc"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("5098992f-b19b-4d4e-adef-e974a5f23c7a"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("bd706ee8-7618-401a-9a24-d2004fdcfcc6"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("95499411-d3b6-4fef-81e3-5ca67683ba8a"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("81acb208-014d-4bfb-8d3a-d2b6655ba17f"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("d38a2e6f-7968-488d-9911-748523baeba6"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("6fcf47eb-c777-4a90-af08-de68033cd498"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("3d7f1d2c-a845-4ae4-89ab-b40522131614"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("b1aba15b-9f3a-479c-a72e-21b2b1e1d99a"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("04e60b05-fd4d-423b-9c3b-23ed3343b4fe"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("a4d65fb7-76e9-4a32-9226-a763a0725735"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("bc496d8d-768a-4e25-9ff6-a99461d919b6"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("1786faca-dd4f-454a-9fb5-a66f22d5af3b"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("9400889b-3da9-4dde-9824-8cdc12ada4ce"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("tblPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("tblPlayerId");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d3caa94-dfdc-4ae0-b18b-f25454b40fb1"),
                            IsPaused = false,
                            Name = "Test Game 1"
                        },
                        new
                        {
                            Id = new Guid("343c4a33-34c0-47e6-8a94-8506b15d2849"),
                            IsPaused = false,
                            Name = "Test Game 2"
                        },
                        new
                        {
                            Id = new Guid("0ed6a3ea-cc17-4f12-8985-9ccbcd62e824"),
                            IsPaused = false,
                            Name = "Test Game 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c11472b9-13c5-4df5-893a-46cf4e3901a7"),
                            Description = "Test Game Log 1",
                            GameId = new Guid("8d3caa94-dfdc-4ae0-b18b-f25454b40fb1"),
                            Timestamp = "Test Stamp 1"
                        },
                        new
                        {
                            Id = new Guid("a6b05d6f-e4cf-492c-b862-b35b6277b27d"),
                            Description = "Test Game Log 2",
                            GameId = new Guid("343c4a33-34c0-47e6-8a94-8506b15d2849"),
                            Timestamp = "Test Stamp 2"
                        },
                        new
                        {
                            Id = new Guid("b58bfa3b-2b0d-48ec-9ecd-cb3cb7b78435"),
                            Description = "Test Game Log 3",
                            GameId = new Guid("0ed6a3ea-cc17-4f12-8985-9ccbcd62e824"),
                            Timestamp = "Test Stamp 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a2f6b5f-5418-4995-ac4c-d53cb4c104ff"),
                            GameId = new Guid("8d3caa94-dfdc-4ae0-b18b-f25454b40fb1"),
                            IsComputerPlayer = false,
                            UserId = new Guid("0408af3b-2af1-4fa3-bfc9-035a7df913ab")
                        },
                        new
                        {
                            Id = new Guid("70360972-df6f-4730-9511-31d4df683c10"),
                            GameId = new Guid("343c4a33-34c0-47e6-8a94-8506b15d2849"),
                            IsComputerPlayer = false,
                            UserId = new Guid("0e029853-c2ee-44ad-be27-8db17b9a9ddf")
                        },
                        new
                        {
                            Id = new Guid("c41496f2-903e-48c4-b0ed-c22da7b4342d"),
                            GameId = new Guid("0ed6a3ea-cc17-4f12-8985-9ccbcd62e824"),
                            IsComputerPlayer = false,
                            UserId = new Guid("8feee8c9-8129-4d7d-9cd0-2218c47b13da")
                        },
                        new
                        {
                            Id = new Guid("40d75b96-caab-4cf1-b514-f470883f347a"),
                            GameId = new Guid("8d3caa94-dfdc-4ae0-b18b-f25454b40fb1"),
                            IsComputerPlayer = true,
                            UserId = new Guid("3e77bbd5-f983-4ccf-a8ee-b04cf08de746")
                        },
                        new
                        {
                            Id = new Guid("5205c7e6-c7ec-4b43-91fa-f3d817efc9f5"),
                            GameId = new Guid("343c4a33-34c0-47e6-8a94-8506b15d2849"),
                            IsComputerPlayer = true,
                            UserId = new Guid("3e77bbd5-f983-4ccf-a8ee-b04cf08de746")
                        },
                        new
                        {
                            Id = new Guid("1a876cbc-8fe0-4a5f-980c-65f8a7c2c6f8"),
                            GameId = new Guid("0ed6a3ea-cc17-4f12-8985-9ccbcd62e824"),
                            IsComputerPlayer = true,
                            UserId = new Guid("3e77bbd5-f983-4ccf-a8ee-b04cf08de746")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c79baff2-6031-4a30-beed-0c4c8b7901ee"),
                            CardId = new Guid("3879e895-5337-4f22-bd6c-ef640630c4c1"),
                            PlayerId = new Guid("8a2f6b5f-5418-4995-ac4c-d53cb4c104ff")
                        },
                        new
                        {
                            Id = new Guid("4167a096-97e1-41c6-b898-947ff0559112"),
                            CardId = new Guid("4ea58f20-d972-477e-a3cd-86b4cd9a8054"),
                            PlayerId = new Guid("70360972-df6f-4730-9511-31d4df683c10")
                        },
                        new
                        {
                            Id = new Guid("4d8e839d-81bd-430f-94c4-068fea1bb46a"),
                            CardId = new Guid("b28ce706-42f1-4f32-b184-541e4f96c928"),
                            PlayerId = new Guid("c41496f2-903e-48c4-b0ed-c22da7b4342d")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0408af3b-2af1-4fa3-bfc9-035a7df913ab"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("0e029853-c2ee-44ad-be27-8db17b9a9ddf"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("8feee8c9-8129-4d7d-9cd0-2218c47b13da"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        },
                        new
                        {
                            Id = new Guid("3e77bbd5-f983-4ccf-a8ee-b04cf08de746"),
                            FirstName = "NPC",
                            LastName = "NPC",
                            Password = "8M1CByOq6EARbI7321yvHg3/Ku8=",
                            Username = "NPC"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", null)
                        .WithMany("Games")
                        .HasForeignKey("tblPlayerId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", null)
                        .WithMany("Games")
                        .HasForeignKey("tblUserId");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
