// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    partial class UNOEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("262db16d-af53-4c2d-ae2f-3ad7d1243681"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e16be3fc-b881-406f-998c-f41ae9ef1ec2"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("959ebf8d-7f46-432f-8f47-37aeeb91e8f5"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("db297066-3397-4cb0-af8a-eaa88d220007"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a12fdbdf-ba30-4374-ba4b-c42a3e618dc9"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f7684dee-9e19-4824-ab27-b9abf96753b5"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4b3628c1-b48f-4e17-88ad-3d54f66bc797"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8958a514-cb64-4c56-aac1-39c8e58f2580"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("3a5c1d71-b85e-4b29-9f59-b2f0d5ee9eb6"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1b7337ba-46f1-43bd-9e19-a63020389246"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("16a1797e-69cc-4b03-a6d1-fea4566486b0"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("94046f74-d212-4fde-a35c-3e1c94d96054"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6e856b67-a729-4d2e-9c9f-40d3e3be9a62"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("d8fe45ed-3782-4bbd-979e-ade60be549ba"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("976b60d7-f8bc-40d4-bdac-bacde7b1ba8e"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("752756c7-bc9d-4225-962e-cf7e7b936c2f"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("45f4d942-8489-4a33-8d97-911062d2cb7c"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6c718b80-fcc5-4230-803f-bc9d4e61d6a9"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("fcd279d2-0ac5-4e0f-8256-8464c27ce191"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2ff0fd18-cc36-4144-9724-b4765448f613"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("13bf0ce7-b685-4bc8-9fdd-e5f7581497ba"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("67146f41-56ee-4915-9298-04fe29019496"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2868994b-69d8-417f-9a25-ffb2cf1ad9f3"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("47a3f208-15b6-469c-aacf-c16dad8100bc"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b4b4d06d-4246-4a59-868c-05fb787f2f8d"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("469ef501-12e7-4c8f-9605-9210ca0f1b73"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6f2129f7-9b85-4057-9e0a-a5c295f023dd"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("442f394a-809b-4552-b441-db24de1a87ca"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("53dd91f5-d302-4890-8c83-e6fde1b6ee3d"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ac29d53f-bf8b-4662-9ab6-92261c94501a"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("471a0e77-3933-4027-8a1b-a889be1a4962"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f11c3a16-6aa6-4658-ba4b-c09eb62cb70e"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("67682896-d7ec-4967-8cdf-987e771afc07"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("adae4ec5-54c3-442a-ab6c-5642578ff295"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ea6191eb-773e-4b31-bf96-a080537d9644"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("819e9a06-c943-48c3-90a1-06942c07eacd"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c997374a-1b77-4d13-aac2-7835f8c06351"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("76d19ac6-b1d9-4bc0-9dfe-40ac61305dbb"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("b31b80da-92ee-4799-ab46-7409326a6be0"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6a316fc4-f677-419f-9dcb-ce363cec0c9e"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7cb465e3-d0f0-4f08-86cb-dc56572dcaa5"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("6dc1f19d-f118-4934-b3b8-c03636fb3250"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("11e6b002-4052-4416-91b3-7ca8e69fc1c3"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("f9650cde-1e44-4a93-8c99-d4449ffb07a0"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("da579f9c-33a0-4a44-9ac4-15ea122041b3"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("3d260ead-36f9-47c7-ab37-f36bab3c802a"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("8f277115-cc7a-4788-862e-f1cbceced82e"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("52004eb5-9b07-4998-b631-32227d5bee79"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("bb19e71a-b963-431e-b6e6-7add5bf69756"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("084ee47a-3c4c-4c8c-8532-a68a154d026a"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("67f12dbb-2c34-43df-bf5e-96a81237c894"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("82cc29bb-85a9-4488-8643-3c7460ba8346"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("51aee0a1-6ac2-4e64-86bb-515dcfbbbdf4"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("ed5ee3af-28ed-4f0c-9a22-8120277cd1c2"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4df33eb-df78-426d-b655-d7da7f28be9f"),
                            IsPaused = false,
                            Name = "TestGame"
                        },
                        new
                        {
                            Id = new Guid("90b95faa-cb23-45a6-a9f2-99935b52fc50"),
                            IsPaused = false,
                            Name = "TestGame2"
                        },
                        new
                        {
                            Id = new Guid("65e93e29-855c-45d1-91ec-2950397a5f1a"),
                            IsPaused = false,
                            Name = "TestGame3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c740bf0f-5809-4870-a306-6a61e439fdf1"),
                            Description = "TestGameLog",
                            GameId = new Guid("b4df33eb-df78-426d-b655-d7da7f28be9f"),
                            Timestamp = "TestStamp"
                        },
                        new
                        {
                            Id = new Guid("8240d4f6-63b7-45f7-a004-71b0d4da2b24"),
                            Description = "TestGameLog2",
                            GameId = new Guid("90b95faa-cb23-45a6-a9f2-99935b52fc50"),
                            Timestamp = "TestStamp2"
                        },
                        new
                        {
                            Id = new Guid("9d1cbd8a-6eb5-4fd4-b543-12ec02cef081"),
                            Description = "TestGameLog3",
                            GameId = new Guid("65e93e29-855c-45d1-91ec-2950397a5f1a"),
                            Timestamp = "TestStamp3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2555215f-a31b-466c-bcfb-5f6ce6eca06b"),
                            GameId = new Guid("b4df33eb-df78-426d-b655-d7da7f28be9f"),
                            IsComputerPlayer = false,
                            UserId = new Guid("aa43fc93-df2b-40c5-a4fd-c97baaf0d86c")
                        },
                        new
                        {
                            Id = new Guid("8b88e38f-a92c-4e26-8f5d-aa9533979be9"),
                            GameId = new Guid("90b95faa-cb23-45a6-a9f2-99935b52fc50"),
                            IsComputerPlayer = false,
                            UserId = new Guid("2abd9301-31f2-4e4a-b58a-125c14529b2c")
                        },
                        new
                        {
                            Id = new Guid("d36317c4-c381-43de-8ff7-ed0fa16f384b"),
                            GameId = new Guid("65e93e29-855c-45d1-91ec-2950397a5f1a"),
                            IsComputerPlayer = false,
                            UserId = new Guid("bcbcfef3-fbc9-40ea-8d43-9e23cf4b8fff")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef11076a-8ab6-4bc7-8318-d60e6ceed188"),
                            CardId = new Guid("262db16d-af53-4c2d-ae2f-3ad7d1243681"),
                            PlayerId = new Guid("2555215f-a31b-466c-bcfb-5f6ce6eca06b")
                        },
                        new
                        {
                            Id = new Guid("2c9ba87b-591a-48b2-be73-7fb5e7fe2aee"),
                            CardId = new Guid("e16be3fc-b881-406f-998c-f41ae9ef1ec2"),
                            PlayerId = new Guid("8b88e38f-a92c-4e26-8f5d-aa9533979be9")
                        },
                        new
                        {
                            Id = new Guid("fd531db6-e8d5-4d05-9c3a-61a7d24275c8"),
                            CardId = new Guid("959ebf8d-7f46-432f-8f47-37aeeb91e8f5"),
                            PlayerId = new Guid("d36317c4-c381-43de-8ff7-ed0fa16f384b")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa43fc93-df2b-40c5-a4fd-c97baaf0d86c"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "Austin"
                        },
                        new
                        {
                            Id = new Guid("2abd9301-31f2-4e4a-b58a-125c14529b2c"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "Carlos"
                        },
                        new
                        {
                            Id = new Guid("bcbcfef3-fbc9-40ea-8d43-9e23cf4b8fff"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "Brian"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", null)
                        .WithMany("Games")
                        .HasForeignKey("tblUserId");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
