// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAM11.UNO.PL.Data;

#nullable disable

namespace TEAM11.UNO.PL.Migrations
{
    [DbContext(typeof(UNOEntities))]
    partial class UNOEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCard_Id");

                    b.ToTable("tblCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f9d0230-193d-4735-8970-ce4865f048cb"),
                            Color = "Red",
                            Name = "R0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("53ada8ff-22b8-42dc-be4b-a3c798efc023"),
                            Color = "Red",
                            Name = "R1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("efefd2ba-87a9-4be8-a36f-5da15e4b11fe"),
                            Color = "Red",
                            Name = "R2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("64d3be1d-553e-41fc-9e5b-c592ff13e162"),
                            Color = "Red",
                            Name = "R3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("57dcbf6e-85ff-4d23-800c-89cd7b670682"),
                            Color = "Red",
                            Name = "R4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("943bb375-ff20-4f2a-8069-5948ae261181"),
                            Color = "Red",
                            Name = "R5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f7d1206f-30e1-4ff7-bd01-785eaef313b9"),
                            Color = "Red",
                            Name = "R6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ccc97e47-52b9-4d8e-bda0-0c7a720b82a3"),
                            Color = "Red",
                            Name = "R7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("04831419-88b0-43ab-9391-65478ffb55e8"),
                            Color = "Red",
                            Name = "R8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("370714df-7c94-47ae-aa8f-e3abd4a10148"),
                            Color = "Red",
                            Name = "R9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("8739ee4b-8c11-4af3-98a7-9f03ee2934dd"),
                            Color = "Blue",
                            Name = "B0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("c5a77811-eb5d-49be-94c4-d4523cc582fc"),
                            Color = "Blue",
                            Name = "B1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f426913c-1c47-42b5-8dc0-45286429174f"),
                            Color = "Blue",
                            Name = "B2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("76ef468d-9fe9-4bc9-a855-b260aaa63d12"),
                            Color = "Blue",
                            Name = "B3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0f7ef2e6-5d7a-4904-ae79-b56f358dbece"),
                            Color = "Blue",
                            Name = "B4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("021cf323-e3b9-47c6-bd57-59339eca19c6"),
                            Color = "Blue",
                            Name = "B5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f9d3652a-40a9-4f42-a4bc-bd9eacab4a82"),
                            Color = "Blue",
                            Name = "B6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("1d9972eb-642e-44e4-86b0-0ffdd8aaa852"),
                            Color = "Blue",
                            Name = "B7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("76a3d3a2-4612-486b-82d6-a9b06763d2f5"),
                            Color = "Blue",
                            Name = "B8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("836472b9-68a0-4d99-a12a-25dceaaf8543"),
                            Color = "Blue",
                            Name = "B9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2c4f3132-ea0c-4f4c-8c26-7f60e4977e98"),
                            Color = "Yellow",
                            Name = "Y0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("6b582133-9e08-4770-b74c-08974c7f44cd"),
                            Color = "Yellow",
                            Name = "Y1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("e9595196-4d38-4b6c-9590-45e8d0aae4c8"),
                            Color = "Yellow",
                            Name = "Y2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("0c2a09ec-0d0d-45b8-82fc-e546eb0d8179"),
                            Color = "Yellow",
                            Name = "Y3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("11c9e169-f14b-4343-8bcd-281ceb166e99"),
                            Color = "Yellow",
                            Name = "Y4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("7cc127e7-8a28-45d9-b3be-99c6858b6e89"),
                            Color = "Yellow",
                            Name = "Y5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ca1adeaf-e26d-4deb-972f-9415c9c1abd3"),
                            Color = "Yellow",
                            Name = "Y6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ef0ae620-71a8-478d-8289-09bd7b5c60af"),
                            Color = "Yellow",
                            Name = "Y7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("442b5fa9-7e52-4dc4-bb44-90c9e7e5cac6"),
                            Color = "Yellow",
                            Name = "Y8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("f4ca0700-da9b-444e-a717-65b019802519"),
                            Color = "Yellow",
                            Name = "Y9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("19170dc6-207f-47e3-8d3d-39f0bfaae131"),
                            Color = "Green",
                            Name = "G0",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("89e7c53c-cc5b-4737-a75a-6b844c7c62c5"),
                            Color = "Green",
                            Name = "G1",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("aff1e2b7-0d81-4884-8bd1-c7dd219a7e46"),
                            Color = "Green",
                            Name = "G2",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("80ebbe2d-2db0-459d-9a06-26ad51aac6f4"),
                            Color = "Green",
                            Name = "G3",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a5728676-c293-4d5a-8ea5-1f767b7ee16c"),
                            Color = "Green",
                            Name = "G4",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("58b9bcae-fab6-41db-8e4f-2c4865ec031f"),
                            Color = "Green",
                            Name = "G5",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("90c247e4-347e-42f2-b76a-0b42f2ab9bd4"),
                            Color = "Green",
                            Name = "G6",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("a5446b93-a580-4769-92bd-640898075abe"),
                            Color = "Green",
                            Name = "G7",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("2c3db21e-04eb-4477-9463-ccb9fb9c31a1"),
                            Color = "Green",
                            Name = "G8",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("ec298186-f8b4-4552-90bb-dca169f947cd"),
                            Color = "Green",
                            Name = "G9",
                            Type = "Number"
                        },
                        new
                        {
                            Id = new Guid("4fb17afe-ee43-4fc3-9354-015b3c467c67"),
                            Color = "Red",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("13d23095-660a-4967-817b-2c9f6a0d2355"),
                            Color = "Red",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("edf0483a-3844-48f8-8f76-503508a98ef2"),
                            Color = "Red",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("864a5c3c-64a5-4acb-84b5-e4f839e31fd0"),
                            Color = "Blue",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("dd4e0636-6603-4d73-b1a9-b9f1e2d41025"),
                            Color = "Blue",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("b993d517-e03e-433c-af75-e59e89abfdde"),
                            Color = "Blue",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("3c44d0b5-ed19-4aed-9267-9e09123bde60"),
                            Color = "Yellow",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("98dd316c-4c6a-46f1-ad9d-146284bea69e"),
                            Color = "Yellow",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("841f12b3-8fb0-4fa8-9c3c-8ace98887f9e"),
                            Color = "Yellow",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("2d49315d-96ea-4c7a-b05a-1f21b22029e5"),
                            Color = "Green",
                            Name = "Skip",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("cda14202-af6d-4a72-ac48-c864f6b17ffc"),
                            Color = "Green",
                            Name = "Reverse",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("64aa1635-d13a-4e29-87c3-9cd5f293d6e9"),
                            Color = "Green",
                            Name = "DrawTwo",
                            Type = "Action"
                        },
                        new
                        {
                            Id = new Guid("10a16a33-5447-4d72-a024-4d40c25d2923"),
                            Color = "Wild",
                            Name = "Wild",
                            Type = "Wild"
                        },
                        new
                        {
                            Id = new Guid("de0950a4-02b6-4ab1-b1a1-0d3de0f2f98d"),
                            Color = "Wild",
                            Name = "Wild Draw Four",
                            Type = "Wild"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentTurnUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("tblPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.HasIndex("tblPlayerId");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2479c7de-df6c-4e51-bc11-b0dd36de2e0e"),
                            CurrentTurnUserId = new Guid("e4181791-678c-47b5-a9a5-d1452639b90c"),
                            IsPaused = false,
                            Name = "Test Game 1"
                        },
                        new
                        {
                            Id = new Guid("5a81e4c5-3fb4-4651-8f17-e57f016f20e0"),
                            CurrentTurnUserId = new Guid("07b444b1-4d9e-4b5f-8177-2f8f29c1285c"),
                            IsPaused = false,
                            Name = "Test Game 2"
                        },
                        new
                        {
                            Id = new Guid("21ab6236-252c-4fea-b2ac-4daa49fc13e1"),
                            CurrentTurnUserId = new Guid("d670c893-a3e7-465b-8ecc-4c53eb6682de"),
                            IsPaused = false,
                            Name = "Test Game 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGameLog_Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblGameLog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("335bdf3e-7ded-42c4-8cfc-199b47e2081c"),
                            Description = "Test Game Log 1",
                            GameId = new Guid("2479c7de-df6c-4e51-bc11-b0dd36de2e0e"),
                            Timestamp = "Test Stamp 1"
                        },
                        new
                        {
                            Id = new Guid("6dadc7cb-a048-4161-b52b-9e2a47229589"),
                            Description = "Test Game Log 2",
                            GameId = new Guid("5a81e4c5-3fb4-4651-8f17-e57f016f20e0"),
                            Timestamp = "Test Stamp 2"
                        },
                        new
                        {
                            Id = new Guid("f88f72e7-3855-4f87-add3-7f0b02e1bab9"),
                            Description = "Test Game Log 3",
                            GameId = new Guid("21ab6236-252c-4fea-b2ac-4daa49fc13e1"),
                            Timestamp = "Test Stamp 3"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a327e95-174e-4e9d-b0c9-36661a33824b"),
                            GameId = new Guid("2479c7de-df6c-4e51-bc11-b0dd36de2e0e"),
                            IsComputerPlayer = false,
                            UserId = new Guid("e4181791-678c-47b5-a9a5-d1452639b90c")
                        },
                        new
                        {
                            Id = new Guid("9c5e0720-8676-4eb3-acb1-0f9696849846"),
                            GameId = new Guid("5a81e4c5-3fb4-4651-8f17-e57f016f20e0"),
                            IsComputerPlayer = false,
                            UserId = new Guid("07b444b1-4d9e-4b5f-8177-2f8f29c1285c")
                        },
                        new
                        {
                            Id = new Guid("62b9c491-f338-482a-a80d-99e87ea4042b"),
                            GameId = new Guid("21ab6236-252c-4fea-b2ac-4daa49fc13e1"),
                            IsComputerPlayer = false,
                            UserId = new Guid("d670c893-a3e7-465b-8ecc-4c53eb6682de")
                        },
                        new
                        {
                            Id = new Guid("6f7344fe-5f42-43d5-9acf-df7d488c49d7"),
                            GameId = new Guid("2479c7de-df6c-4e51-bc11-b0dd36de2e0e"),
                            IsComputerPlayer = true,
                            UserId = new Guid("48ac6cb5-969d-45e9-b814-3950e1840024")
                        },
                        new
                        {
                            Id = new Guid("05c6b452-740e-41b0-a2ea-80e28a6d43aa"),
                            GameId = new Guid("5a81e4c5-3fb4-4651-8f17-e57f016f20e0"),
                            IsComputerPlayer = true,
                            UserId = new Guid("48ac6cb5-969d-45e9-b814-3950e1840024")
                        },
                        new
                        {
                            Id = new Guid("36f5fe6d-c8cb-4823-b0b5-eb79a5f73410"),
                            GameId = new Guid("21ab6236-252c-4fea-b2ac-4daa49fc13e1"),
                            IsComputerPlayer = true,
                            UserId = new Guid("48ac6cb5-969d-45e9-b814-3950e1840024")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerCard_Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerCard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("63476741-dc73-4821-8891-29fa910162f1"),
                            CardId = new Guid("9f9d0230-193d-4735-8970-ce4865f048cb"),
                            PlayerId = new Guid("3a327e95-174e-4e9d-b0c9-36661a33824b")
                        },
                        new
                        {
                            Id = new Guid("712b97e3-873b-47b7-98f2-9a413a52339f"),
                            CardId = new Guid("53ada8ff-22b8-42dc-be4b-a3c798efc023"),
                            PlayerId = new Guid("9c5e0720-8676-4eb3-acb1-0f9696849846")
                        },
                        new
                        {
                            Id = new Guid("6173860b-ff39-47c7-8683-27cfe08ba896"),
                            CardId = new Guid("efefd2ba-87a9-4be8-a36f-5da15e4b11fe"),
                            PlayerId = new Guid("62b9c491-f338-482a-a80d-99e87ea4042b")
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4181791-678c-47b5-a9a5-d1452639b90c"),
                            FirstName = "Austin",
                            LastName = "Steffes",
                            Password = "Wwbx8IUDtOY0aSZmfTGPD51+n9E=",
                            Username = "asteffes"
                        },
                        new
                        {
                            Id = new Guid("07b444b1-4d9e-4b5f-8177-2f8f29c1285c"),
                            FirstName = "Carlos",
                            LastName = "Guzman",
                            Password = "ZRhJY7TwwZ8UzKABa1uS7MYtnfQ=",
                            Username = "cguzman"
                        },
                        new
                        {
                            Id = new Guid("d670c893-a3e7-465b-8ecc-4c53eb6682de"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "dcRQw/ljvvuRLuefC2PlY2UngPA=",
                            Username = "bfoote"
                        },
                        new
                        {
                            Id = new Guid("48ac6cb5-969d-45e9-b814-3950e1840024"),
                            FirstName = "NPC",
                            LastName = "NPC",
                            Password = "8M1CByOq6EARbI7321yvHg3/Ku8=",
                            Username = "nonplayercharacter"
                        });
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", null)
                        .WithMany("Games")
                        .HasForeignKey("tblPlayerId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", null)
                        .WithMany("Games")
                        .HasForeignKey("tblUserId");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGameLog", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Gamelogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblGameLog_GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_GameId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayer_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayerCard", b =>
                {
                    b.HasOne("TEAM11.UNO.PL.Entities.tblCard", "Card")
                        .WithMany("Playercards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_CardId");

                    b.HasOne("TEAM11.UNO.PL.Entities.tblPlayer", "Player")
                        .WithMany("Playercards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblPlayerCard_PlayerId");

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblCard", b =>
                {
                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblGame", b =>
                {
                    b.Navigation("Gamelogs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Playercards");
                });

            modelBuilder.Entity("TEAM11.UNO.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
